#!/bin/bash

help() {
    printf "Usage: create [flags] [filename]\nFlags:\ne) set file executable\nh) help\nn) Do not save creation time and date\n"
}

error() {
    printf "Incorrect Option! Use -h to get help"
}

n=true

while getopts ":ehn" opt; do
    case $opt in
        e) e=true;;
        h) 
            help 
            exit 1
            ;;
        n) n=false;;
        \?) 
            error
            exit 1;
    esac
done
shift $((OPTIND -1))

touch $1 &
wait

if [ $e ]; then
    chmod u+x $1
fi

if [ $n ]; then
    pwd=$(pwd)
    date=$(date)
    cd
    echo "$pwd/$1 $date" >> creation.txt
fi