#!/bin/bash

help() {
    printf "Usage: curcon [flags] [CURRENCYCODE]\n
Flags:
    o) Show the opposite rate
    h) to show this page\n"
}

error() {
    printf "Incorrect Option! Use -h to get help"
}

oppflag=0

while getopts ":oh" opt; do
    case $opt in
        o) oppflag=1;;
        h) help; exit 1;;
        \?) error; exit 1;;
    esac
done
shift $((OPTIND -1))

if [[ $oppflag -eq 1 ]]; then
    curl http://www.floatrates.com/daily/usd.json | jq .$1 | jq '.inverseRate'
else
    curl http://www.floatrates.com/daily/usd.json | jq .$1 | jq '.rate'
fi